name: dependency_container
description: A simple flutter dependency container which is based on a Map, providing support for factories.
version: 0.1.3
homepage: https://github.com/sterlp/dependency_container

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lint: ^2.0.1
  test: ^1.17.9
